# https://pre-commit.com/
# pre-commit install
# pre-commit run --all-files

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: [--style=file]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^tests/data/invalid_bad_yaml\.yaml$

      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

exclude: |
  (?x)^(
    build/|
    \.build/|
    \.cache/
  )
